<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\App;

class AdminSetting extends Model
{
    CONST DEF_DB_UN = 'def_db_un';
    CONST DEF_DB_PW = 'def_db_pw';
    CONST DEF_DB_NAME = 'def_db_name';
    CONST DEF_STRIPE_PUB = 'stripe_pub';
    CONST DEF_STRIPE_SEC = 'stripe_sec';

    protected $guarded = [];

    /**
     * @param
     * @return array Stripe keys
     */
    public static function getStripeKey($key = null) {
        try
        {
            //todo:for now i just hardcoded that always take test stripe keys.
            $test = true;

            if ($test)
                $stripe_keys = self::query()->where('scope' , 'Test Api key')->pluck('value' , 'slug')->toArray();
            else
                $stripe_keys = self::query()->where('scope' , 'Live Api key')->pluck('value' , 'slug')->toArray();

            if (empty($stripe_keys))
            {
                $stripe_keys['stripe_pub'] = env('STRIPE_KEY');
                $stripe_keys['stripe_sec'] = env('STRIPE_SECRET');
            }
        }catch (\Exception $exception){
            $stripe_keys['stripe_pub'] = null;
            $stripe_keys['stripe_sec'] = null;
        }

        return $key?$stripe_keys[$key]:$stripe_keys;
    }

    protected static function boot()
    {
//        parent::boot(); // TODO: Change the autogenerated stub

        static::updated(function($model)
        {
            if ( in_array($model->slug , [self::DEF_STRIPE_PUB , self::DEF_STRIPE_SEC] ))
            {
                set_file_value($model->slug , $model->value);
//                dd(base_path('config/admin_settings.php'));
            }
        });
    }

}
